#!/usr/bin/env python
"""Quality gate: run every provided sample answer end to end and check invariants.

Two jobs:

  1. Produce the evidence the brief asks for - each sample's transcript,
     retrieval, branch decision and score, written to a markdown report.
  2. Fail loudly on the things that would silently rot. Scores from a 7B model
     move a little run to run, so asserting exact scores would just produce a
     flaky gate. Instead we assert the properties that must not change, and
     compare scores against a stored baseline with a tolerance.

Checks:
  * retrieval precision - the two irrelevant reference notes (dependency
    injection, API security) must stay out of the retrieved set
  * language fidelity   - Arabic in must produce Arabic out
  * schema validity     - score in 1-5, justification non-empty
  * decision audit      - every run records a branch decision with a reason
  * score drift         - vs tests/golden/quality_gate.json, tolerance +/-1

Usage:
    python scripts/run_quality_gate.py
    python scripts/run_quality_gate.py --update-golden   # accept current scores
"""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from voice_agent.agent import ScreeningAgent  # noqa: E402
from voice_agent.config import ARTIFACT_DIR, AUDIO_DIR  # noqa: E402
from voice_agent.schemas import TurnResult  # noqa: E402

# Not relevant to a "slow endpoint under load" question. They exist in the
# corpus as distractors; retrieving them means the embedder is not discriminating.
DISTRACTOR_DOCS = {"02_dependency_injection", "04_api_design_security"}

GOLDEN_PATH = REPO_ROOT / "tests" / "golden" / "quality_gate.json"
REPORT_PATH = REPO_ROOT / "docs" / "QUALITY_GATE_RESULTS.md"
SCORE_TOLERANCE = 1


def has_arabic(text: str) -> bool:
    return any(
        0x0600 <= ord(c) <= 0x06FF or 0xFB50 <= ord(c) <= 0xFEFF
        for c in text
        if unicodedata.category(c).startswith("L")
    )


def check(result: TurnResult, name: str) -> list[str]:
    failures: list[str] = []

    hit = {c.doc_id for c in result.retrieved} & DISTRACTOR_DOCS
    if hit:
        failures.append(f"{name}: retrieval pulled in irrelevant docs {sorted(hit)}")

    if result.transcript.language == "ar":
        if not has_arabic(result.evaluation.justification):
            failures.append(
                f"{name}: answer was Arabic but justification came back without Arabic script"
            )
    elif has_arabic(result.evaluation.justification):
        failures.append(f"{name}: answer was English but justification came back in Arabic")

    if not 1 <= result.evaluation.score <= 5:
        failures.append(f"{name}: score {result.evaluation.score} outside 1-5")
    if not result.evaluation.justification.strip():
        failures.append(f"{name}: empty justification")
    if not result.transcript.text.strip():
        failures.append(f"{name}: empty transcript")
    if not result.decision.reason.strip():
        failures.append(f"{name}: branch decision has no recorded reason")

    return failures


def summarise(name: str, r: TurnResult) -> dict:
    return {
        "sample": name,
        "language": r.transcript.language,
        "arabic_ratio": round(r.transcript.arabic_ratio, 3),
        "duration_s": round(r.transcript.duration_s or 0, 1),
        "transcript": r.transcript.text,
        "retrieved_competencies": [
            c.section.replace("Competency:", "").strip()
            for c in r.retrieved
            if c.doc_id == "00_scoring_rubric"
        ],
        "retrieved_references": sorted(
            {c.doc_id for c in r.retrieved if c.doc_id != "00_scoring_rubric"}
        ),
        "coverage": {a.competency: a.status.value for a in r.coverage.assessments},
        "followed_up": r.decision.should_follow_up,
        "decision_reason": r.decision.reason,
        "follow_up_question": r.decision.question,
        "score": r.evaluation.score,
        "justification": r.evaluation.justification,
        "covered": r.evaluation.covered,
        "missed": r.evaluation.missed,
    }


def render_report(rows: list[dict], failures: list[str]) -> str:
    out = [
        "# Quality Gate Results",
        "",
        "Generated by `scripts/run_quality_gate.py`. Each provided sample answer is run",
        "through the full pipeline: transcribe → retrieve → assess coverage → branch → score.",
        "",
        "In batch mode no human is present to answer a clarifying question, so when the",
        "agent decides to follow up, the question it composed is recorded and scoring",
        "falls back to the original answer. The branch is still exercised and logged.",
        "",
        "| Sample | Lang | Followed up | Score | Justification |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        just = r["justification"].replace("|", "\\|")
        out.append(
            f"| {r['sample']} | `{r['language']}` | "
            f"{'yes' if r['followed_up'] else 'no'} | **{r['score']}/5** | {just} |"
        )

    out += ["", "---", ""]
    for r in rows:
        out += [
            f"## {r['sample']}",
            "",
            f"- **Language detected:** `{r['language']}` (Arabic script {r['arabic_ratio']:.0%}) · {r['duration_s']}s",
            f"- **Competencies retrieved:** {', '.join(r['retrieved_competencies']) or '—'}",
            f"- **Reference notes retrieved:** {', '.join(r['retrieved_references']) or '—'}",
            "",
            "**Transcript**",
            "",
            f"> {r['transcript']}",
            "",
            "**Coverage**",
            "",
        ]
        out += [f"- {k}: `{v}`" for k, v in r["coverage"].items()]
        out += [
            "",
            f"**Branch decision:** {'ask a follow-up' if r['followed_up'] else 'move on and score'}",
            "",
            f"> {r['decision_reason']}",
            "",
        ]
        if r["follow_up_question"]:
            out += [f"**Follow-up composed:** {r['follow_up_question']}", ""]
        out += [
            f"**Score:** {r['score']}/5 — {r['justification']}",
            "",
            f"- Covered: {', '.join(r['covered']) or '—'}",
            f"- Missed: {', '.join(r['missed']) or '—'}",
            "",
        ]

    out += ["---", "", "## Gate status", ""]
    out.append("✅ All checks passed." if not failures else "❌ Failures:")
    out += [f"- {f}" for f in failures]
    out += [
        "",
        "## How I'd know a change made this worse",
        "",
        "The gate pins the things that should never move and tolerates the one thing that",
        "legitimately does. Retrieval precision is binary: the two irrelevant reference notes",
        "(dependency injection, API security) must stay out of the retrieved set, and if a",
        "chunking or embedding change lets them in, retrieval has stopped discriminating.",
        "Language fidelity is likewise binary: an Arabic answer that comes back scored in",
        "English is a regression no score comparison would catch. Scores themselves I treat as",
        "noisy, so they are compared against a stored baseline with a ±1 tolerance — a single",
        "sample drifting one point is sampling noise, but two samples moving together, or any",
        "sample moving two points, means the prompt or model change altered the scoring band",
        "and needs a human to look. The branch decisions are also snapshotted: if a sample that",
        "used to earn a follow-up stops earning one, the coverage pass has changed its",
        "partial/missing calibration even when the final score happens to land the same.",
    ]
    return "\n".join(out)


def run_gate(
    agent: "ScreeningAgent | None" = None,
    samples: "list[str] | None" = None,
    speak: bool = False,
    update_golden: bool = False,
) -> int:
    """Run the gate, optionally against an already-loaded agent.

    Pass `agent` when calling from a notebook that has models resident. Spawning
    this as a subprocess instead loads a second copy of Whisper and BGE-M3 into
    VRAM, and on a 15 GB T4 that is enough to push Ollama off the GPU and onto
    the CPU, where generation is slow enough to hit the request timeout.
    """
    files = (
        [AUDIO_DIR / s for s in samples] if samples else sorted(AUDIO_DIR.glob("*.mp3"))
    )
    if not files:
        print(f"No sample audio found in {AUDIO_DIR}", file=sys.stderr)
        return 2

    agent = agent or ScreeningAgent()
    ok, msg = agent.llm.health()
    print("LLM: " + msg)
    if not ok:
        print("Aborting - the LLM must be reachable to run the gate.", file=sys.stderr)
        return 2

    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    rows: list[dict] = []
    failures: list[str] = []

    for path in files:
        print(f"\n=== {path.name} ===")
        result = agent.run(
            str(path),
            follow_up_provider=None,  # batch: record the decision, score the original
            speak=speak,
            out_path=ARTIFACT_DIR / f"{path.stem}_evaluation.wav",
        )
        row = summarise(path.name, result)
        rows.append(row)
        failures.extend(check(result, path.name))
        print(f"  lang={row['language']} follow_up={row['followed_up']} score={row['score']}/5")
        print(f"  {row['justification']}")

    # Score drift against the baseline.
    if GOLDEN_PATH.exists() and not update_golden:
        golden = {r["sample"]: r for r in json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))}
        drifted = 0
        for row in rows:
            prev = golden.get(row["sample"])
            if not prev:
                continue
            delta = abs(row["score"] - prev["score"])
            if delta > SCORE_TOLERANCE:
                failures.append(
                    f"{row['sample']}: score moved {prev['score']} -> {row['score']} "
                    f"(> ±{SCORE_TOLERANCE})"
                )
            elif delta:
                drifted += 1
            if prev.get("followed_up") != row["followed_up"]:
                failures.append(
                    f"{row['sample']}: branch flipped "
                    f"({prev.get('followed_up')} -> {row['followed_up']})"
                )
        if drifted >= 2:
            failures.append(
                f"{drifted} samples each drifted a point in the same run - "
                "individually tolerable, together a signal the scoring band shifted."
            )
    elif update_golden or not GOLDEN_PATH.exists():
        GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN_PATH.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"\nBaseline written to {GOLDEN_PATH.relative_to(REPO_ROOT)}")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(render_report(rows, failures), encoding="utf-8")
    (ARTIFACT_DIR / "quality_gate.json").write_text(
        json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print(f"\nReport: {REPORT_PATH.relative_to(REPO_ROOT)}")
    if failures:
        print("\n❌ QUALITY GATE FAILED")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("\n✅ QUALITY GATE PASSED")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update-golden", action="store_true")
    parser.add_argument("--no-speak", action="store_true", help="skip TTS to run faster")
    parser.add_argument("--samples", nargs="*", help="filenames under assets/audio")
    args = parser.parse_args()
    return run_gate(
        samples=args.samples,
        speak=not args.no_speak,
        update_golden=args.update_golden,
    )


if __name__ == "__main__":
    raise SystemExit(main())
